M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-07-20T12:57:25
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-20T12:57:25-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X16.5Y-16.9
X16.5Y-70.85
X60.8Y-70.85
X91.0Y-16.9
M30
